stages:
  - compile
  - deploy

scss-job:
  stage: compile
  image: node:lts
  script:
    - yarn global add sass
    - mkdir -p versions/latest
    - cp `find versions -regextype egrep -type d -iregex 'versions/[0-9]+\..*' | sort --version-sort | tail -1`/style.scss versions/latest/style.scss
    - sass --style=compressed versions/latest/style.scss versions/latest/style.min.css
    - for major in $(find versions -regextype egrep -type d -iregex 'versions/[0-9]+\.[0-9]+.x' |  awk -F '.' '{print substr($1,8)}' | sort -n | uniq); do mkdir -p "versions/$major.x.x"; cp versions/$(find versions -regextype egrep -type d -iregex "versions/$major\.[0-9]+.x" | awk -F '/' '{print $2}' | sort --version-sort | tail -1)/style.scss "versions/$major.x.x/style.scss"; sass --style=compressed "versions/$major.x.x/style.scss" "versions/$major.x.x/style.min.css"; done
    - cp index.html versions/index.html
    - cp star.svg versions/star.svg
  artifacts:
    paths:
    - versions
  only:
  - master

pages:
  stage: deploy
  script:
    - echo 'Placeholder'
  artifacts:
    paths:
    - versions
  only:
  - master
